### ISSUE TITLE
error websocket connection closed om

### ISSUE THREAD

**Issue by baztardengine** [Widiskel/prick-autotap-bot#1]
om error om websocket connection closed
server prick nya nge closed koneksi waktu mau nge tap

**Comment by Widiskel** [comment]
iya bg msh belum nemu solusi buat itu , mslhnya yg eror cmn di beberapa akun aja. akun utama gw aman , akun tuyul gabisa tap smua.. bukan dr botnya itu gw buka gamenya di tele pun akun yg problem walaupun udah tap, pas relog energynya full lg poin ga keitung

**Comment by heisenbergxxxs** [comment]
bang izin tanya, udah nambahin id tele buat prick, tapi kok gabisa ya?

ada contoh cara isi id tele di bot prick nya??

**Comment by heisenbergxxxs** [comment]
bang izin tanya, udah nambahin id tele buat prick, tapi kok gabisa ya?

ada contoh cara isi id tele di bot prick nya??

**Comment by Widiskel** [comment]
kyknya prick ini skip dlu dah, msh belum stabil servernya web socketnya eror trus, nunggu agak stabil nanti gw update lg

**Comment by baztardengine** [comment]
harus di buka dlu telegram bot nya om baru running bot python nya dia bisa.
tapi g bisa multi..kalau akun tele nya ga d buka ga mau dia langsung closed koneksi

**Comment by baztardengine** [comment]
om gua boleh bantu2 analisa ga om prick nya ?
gua udah coba tes kalau bot nya di bikin dari awal dia langsung fill energy dlu, bot nya lancar om. jadi pas running mau posisi akun nya lagi 0 energy nya ataupun penuh langsung timpa satu kali wajib fill energy dlu maka bot nya lancar. server prick nya kayak nge block bot python nya kalau ga fill energy dlu langsung di tendang sama server nya jadi dc.
nah masalah nya ketika akun nya posisi nya ga bisa refill energy dan g bisa aktifin turbo maka bot nya jadi error krn gua ga bisa coding om cuma bisa pindah2in perintah aja wkkwkw ga ngerti cara ngakali nya. harus di bikin kalau posisi akun nya ga bisa refill energy atau ga bisa aktifin turbo maka lanjut ke akun kedua.
dan tampilan energy di akun tele prick nya itu sengaja di bikin error sama dev nya. kalau kita aktifin turbo atau fill energy dari bot python bukan klik manual dari dalam akun tele nya maka tulisan  energy nya dan turbo nya tetap 3/3. jadi bot nya di bikin kacau.
padahal turbo dan energy nya udah di pake..pas kita tekan ada tulisan already use status respon 400 gtu om

**Comment by baztardengine** [comment]
om gua boleh bantu2 analisa ga om prick nya ?
gua udah coba tes kalau bot nya di bikin dari awal dia langsung fill energy dlu, bot nya lancar om. jadi pas running mau posisi akun nya lagi 0 energy nya ataupun penuh langsung timpa satu kali wajib fill energy dlu maka bot nya lancar. server prick nya kayak nge block bot python nya kalau ga fill energy dlu langsung di tendang sama server nya jadi dc.
nah masalah nya ketika akun nya posisi nya ga bisa refill energy dan g bisa aktifin turbo krn udah di pake maka bot nya jadi error. gua ga bisa coding om cuma bisa pindah2in perintah aja wkkwkw ga ngerti cara ngakali nya. harus di bikin kalau posisi akun nya ga bisa refill energy atau ga bisa aktifin turbo maka lanjut ke akun kedua.
dan tampilan energy di akun tele prick nya itu sengaja di bikin error sama dev nya. kalau kita aktifin turbo atau fill energy dari bot python bukan klik manual dari dalam akun tele nya maka tulisan energy nya dan turbo nya tetap 3/3. jadi bot nya di bikin kacau.
padahal turbo dan energy nya udah di pake..pas kita tekan ada tulisan already use status respon 400 gtu om
